tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.

filter:
    excluded_paths:
        - tests/*
        - Tests/*
        - spec/*
        - unit/*
        - src/OpSiteBuilder/Bundle/CoreBundle/Tests/*
