parameters:
    lp_factory.page_dynamic_router.class: LpFactory\Bundle\CoreBundle\Routing\PageDynamicRouter
    lp_factory.routing.generator.class: Symfony\Cmf\Component\Routing\ContentAwareGenerator
    lp_factory.route_provider.class: LpFactory\Bundle\CoreBundle\Routing\Provider\PageRouteProvider
    lp_factory.candidates.page.class: LpFactory\Bundle\CoreBundle\Routing\PageCandidates
    lp_factory.route_factory.class: LpFactory\Bundle\CoreBundle\Routing\Factory\PageRouteFactory
    lp_factory.route_configuration.chain.class: LpFactory\Bundle\CoreBundle\Routing\Configuration\PageRouteConfigurationChain
    lp_factory.routing.satinizer.chain.class: LpFactory\Bundle\CoreBundle\Routing\Satinizer\UrlSatinizerChain
    lp_factory.routing.satinizer_format.class: LpFactory\Bundle\CoreBundle\Routing\Satinizer\UrlFormatSatinizer
    lp_factory.routing.final_matcher.class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
    lp_factory.route_strategy.single_tree.class: LpFactory\Bundle\CoreBundle\Routing\Strategy\SingleTreeStrategy

services:
    lp_factory.page_dynamic_router:
        class: %lp_factory.page_dynamic_router.class%
        arguments:
            - @router.request_context
            - @lp_factory.route_configuration.chain
            - @lp_factory.route_provider
            - @lp_factory.routing.final_matcher
            - @lp_factory.routing.generator

    lp_factory.routing.generator:
        class: %lp_factory.routing.generator.class%
        arguments:
            - @lp_factory.route_provider
            - @?logger

    lp_factory.route_provider:
        class: %lp_factory.route_provider.class%
        arguments:
            - @lp_factory.route_factory
            - @lp_factory.routing.satinizer.chain
            - @lp_factory.route_configuration.chain
            - @lp_factory.route_strategy.single_tree

    lp_factory.route_factory:
        class: %lp_factory.route_factory.class%
        arguments:
            - @lp_factory.repository.page
            - @lp_factory.route_strategy.single_tree

    lp_factory.route_configuration.chain:
        class: %lp_factory.route_configuration.chain.class%
        arguments:
            - %lpfactory.route_configuration.class%

    lp_factory.routing.satinizer.chain:
        class: %lp_factory.routing.satinizer.chain.class%

    lp_factory.routing.satinizer_format:
        class: %lp_factory.routing.satinizer_format.class%
        tags:
            - { name: lp_factory.routing.satinizer }

    lp_factory.routing.matcher.dummy_collection:
        class: Symfony\Component\Routing\RouteCollection
        public: false

    lp_factory.routing.matcher.dummy_context:
        class: Symfony\Component\Routing\RequestContext
        public: false

    lp_factory.routing.final_matcher:
        class: %lp_factory.routing.final_matcher.class%
        arguments:
            - @lp_factory.routing.matcher.dummy_collection
            - @lp_factory.routing.matcher.dummy_context

    lp_factory.route_strategy.abstract:
        abstract: true
        arguments:
            - @lp_factory.repository.page

    lp_factory.route_strategy.single_tree:
        parent: lp_factory.route_strategy.abstract
        class: %lp_factory.route_strategy.single_tree.class%

