parameters:
    doctrine.event_listener.page.discriminator_map.class: LpFactory\Bundle\CoreBundle\Doctrine\EventListener\MapDiscriminatorListener
    doctrine.event_listener.block.discriminator_map.class: LpFactory\Bundle\CoreBundle\Doctrine\EventListener\MapDiscriminatorListener

services:
    doctrine.orm.listeners.resolve_target_entity:
        class: %doctrine.orm.listeners.resolve_target_entity.class%
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    doctrine.event_listener.page.discriminator_map:
        class: %doctrine.event_listener.page.discriminator_map.class%
        arguments:
            - %lpfactory.entity.page.class%
            - @lp_factory.page.map
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    doctrine.event_listener.block.discriminator_map:
        class: %doctrine.event_listener.block.discriminator_map.class%
        arguments:
            - %lpfactory.entity.block.class%
            - @lp_factory.block.map.chain
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
