parameters:
    lp_factory.security.page.allow_all.voter.class: LpFactory\Bundle\CoreBundle\Security\AllowAllPageVoter

services:
    lp_factory.security.page.allow_all.voter:
        class: %lp_factory.security.page.allow_all.voter.class%
        public: false
        tags:
            - { name: security.voter }
