lp_factory_api_add_block_to_page:
    path: /page/{id}/block/{type}.json
    defaults:
        _controller: LpFactoryCoreBundle:Page:addBlock
    methods:
        - POST

lp_factory_api_move_block:
    path: /page/{id}/block/{blockId}/move
    defaults:
        _controller: LpFactoryCoreBundle:Page:moveBlock
    methods:
        - PUT

lp_factory_api_view_block:
    path: /block/{id}
    defaults:
        _controller: LpFactoryCoreBundle:Block:view
    methods:
        - GET

lp_factory_api_remove_block:
    path: /block/{id}
    defaults:
        _controller: LpFactoryCoreBundle:Block:remove
    methods:
        - DELETE

lp_factory_api_edit_no_form_block:
    path: /block/{id}/no-form-edit
    defaults:
        _controller: LpFactoryCoreBundle:Block:edit
    methods:
        - GET

lp_factory_api_edit_form_block:
    path: /block/{id}/edit
    defaults:
        _controller: LpFactoryCoreBundle:Block:editForm
    methods:
        - GET
        - POST
