lpfactorydb:
    image: mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=lpfactory

lpfactoryweb:
    build: .
    links:
        - lpfactorydb
    ports:
        - 80:80
    volumes:
        - ../../:/var/www/html
