OpSiteBuilder\Bundle\CoreBundle\Entity\Page:
    type: entity
    table: pages
    manyToOne:
        parent:
            targetEntity: OpSiteBuilder\Bundle\CoreBundle\Model\AbstractPage
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: OpSiteBuilder\Bundle\CoreBundle\Model\AbstractPage
            mappedBy: parent
        blocks:
            targetEntity: OpSiteBuilder\Bundle\CoreBundle\Model\AbstractBlock
            mappedBy: page