LpFactory\Bundle\CoreBundle\Entity\Block:
    type: entity
    table: blocks
    repositoryClass: LpFactory\Bundle\CoreBundle\Entity\Repository\BlockRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: string
        length: 255
    manyToOne:
        page:
            orderBy: { 'sort': 'ASC' }
            targetEntity: LpFactory\Bundle\CoreBundle\Model\AbstractPage
            inversedBy: blocks
            joinColumn:
                name: page_id
                referencedColumnName: id
                onDelete: CASCADE
