parameters:
    opsite_builder.block.manager.class: OpSiteBuilder\Bundle\CoreBundle\Block\BlockManager
    opsite_builder.block.data_provider.chain.class: OpSiteBuilder\Bundle\CoreBundle\Block\Provider\BlockDataProviderChain
    opsite_builder.block.data_provider.default.class: OpSiteBuilder\Bundle\CoreBundle\Block\Provider\DefaultDataProvider
    opsite_builder.block.configuration.chain.class: OpSiteBuilder\Bundle\CoreBundle\Block\Configuration\BlockConfigurationChain
    opsite_builder.block.configuration.default.class: OpSiteBuilder\Bundle\CoreBundle\Block\Configuration\BlockConfiguration
    opsite_builder.block.factory.class: OpSiteBuilder\Bundle\CoreBundle\Block\BlockFactory
    opsite_builder.block.strategy.position.class: OpSiteBuilder\Bundle\CoreBundle\Block\Strategy\BlockPositionStrategy
    opsite_builder.block.renderer.class: OpSiteBuilder\Bundle\CoreBundle\Block\Rendered\BlockRenderer
    opsite_builder.block.map.chain.class: OpSiteBuilder\Bundle\CoreBundle\Block\Configuration\BlockMapChain
    opsite_builder.block.map.default.class: OpSiteBuilder\Bundle\CoreBundle\Block\Configuration\BlockMap

services:
    opsite_builder.block.data_provider.chain:
        class: %opsite_builder.block.data_provider.chain.class%

    opsite_builder.block.manager:
        class: %opsite_builder.block.manager.class%
        arguments:
            - @opsite_builder.block.data_provider.chain
            - @doctrine.orm.entity_manager

    opsite_builder.block.renderer:
        class: %opsite_builder.block.renderer.class%
        arguments:
            - @opsite_builder.block.manager
            - @opsite_builder.block.configuration.chain
            - @templating

    opsite_builder.block.data_provider.default:
        class: %opsite_builder.block.data_provider.default.class%
        tags:
            - { name: opsite_builder.block.data_provider, alias: default }

    opsite_builder.block.configuration.chain:
        class: %opsite_builder.block.configuration.chain.class%

    opsite_builder.block.factory:
        class: %opsite_builder.block.factory.class%
        arguments:
            - @opsite_builder.block.map.chain

    opsite_builder.block.strategy.position:
        class: %opsite_builder.block.strategy.position.class%

    opsite_builder.block.map.chain:
        class: %opsite_builder.block.map.chain.class%
