parameters:
    opsite_builder.page_dynamic_router.class: OpSiteBuilder\Bundle\CoreBundle\Routing\PageDynamicRouter
    opsite_builder.routing.generator.class: Symfony\Cmf\Component\Routing\ContentAwareGenerator
    opsite_builder.route_provider.class: OpSiteBuilder\Bundle\CoreBundle\Routing\Provider\PageRouteProvider
    opsite_builder.candidates.page.class: OpSiteBuilder\Bundle\CoreBundle\Routing\PageCandidates
    opsite_builder.route_factory.class: OpSiteBuilder\Bundle\CoreBundle\Routing\Factory\PageRouteFactory
    opsite_builder.route_configuration.chain.class: OpSiteBuilder\Bundle\CoreBundle\Routing\Configuration\PageRouteConfigurationChain
    opsite_builder.routing.satinizer.chain.class: OpSiteBuilder\Bundle\CoreBundle\Routing\Satinizer\UrlSatinizerChain
    opsite_builder.routing.satinizer_format.class: OpSiteBuilder\Bundle\CoreBundle\Routing\Satinizer\UrlFormatSatinizer
    opsite_builder.routing.final_matcher.class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
    opsite_builder.route_strategy.single_tree.class: OpSiteBuilder\Bundle\CoreBundle\Routing\Strategy\SingleTreeStrategy

services:
    opsite_builder.page_dynamic_router:
        class: %opsite_builder.page_dynamic_router.class%
        arguments:
            - @router.request_context
            - @opsite_builder.route_configuration.chain
            - @opsite_builder.route_provider
            - @opsite_builder.routing.final_matcher
            - @opsite_builder.routing.generator

    opsite_builder.routing.generator:
        class: %opsite_builder.routing.generator.class%
        arguments:
            - @opsite_builder.route_provider
            - @?logger

    opsite_builder.route_provider:
        class: %opsite_builder.route_provider.class%
        arguments:
            - @opsite_builder.route_factory
            - @opsite_builder.routing.satinizer.chain
            - @opsite_builder.route_configuration.chain
            - @opsite_builder.route_strategy.single_tree

    opsite_builder.route_factory:
        class: %opsite_builder.route_factory.class%
        arguments:
            - @opsite_builder.repository.page
            - @opsite_builder.route_strategy.single_tree

    opsite_builder.route_configuration.chain:
        class: %opsite_builder.route_configuration.chain.class%
        arguments:
            - %opsite.route_configuration.class%

    opsite_builder.routing.satinizer.chain:
        class: %opsite_builder.routing.satinizer.chain.class%

    opsite_builder.routing.satinizer_format:
        class: %opsite_builder.routing.satinizer_format.class%
        tags:
            - { name: opsite_builder.routing.satinizer }

    opsite_builder.routing.matcher.dummy_collection:
        class: Symfony\Component\Routing\RouteCollection
        public: false

    opsite_builder.routing.matcher.dummy_context:
        class: Symfony\Component\Routing\RequestContext
        public: false

    opsite_builder.routing.final_matcher:
        class: %opsite_builder.routing.final_matcher.class%
        arguments:
            - @opsite_builder.routing.matcher.dummy_collection
            - @opsite_builder.routing.matcher.dummy_context

    opsite_builder.route_strategy.abstract:
        abstract: true
        arguments:
            - @opsite_builder.repository.page

    opsite_builder.route_strategy.single_tree:
        parent: opsite_builder.route_strategy.abstract
        class: %opsite_builder.route_strategy.single_tree.class%

