parameters:
    opsite.entity.page.class: OpSiteBuilder\Bundle\CoreBundle\Entity\Page
    opsite.entity.block.class: OpSiteBuilder\Bundle\CoreBundle\Entity\Block

    opsite.route_configuration.class: OpSiteBuilder\Bundle\CoreBundle\Routing\Configuration\PageRouteConfiguration
