services:
    opsite_builder.repository.page:
        class: OpSiteBuilder\Bundle\CoreBundle\Model\Repository\PageRepositoryInterface
        factory:
            - @doctrine
            - "getRepository"
        arguments:
            - %opsite.entity.page.class%

    opsite_builder.repository.block:
        class: OpSiteBuilder\Bundle\CoreBundle\Model\Repository\BlockRepositoryInterface
        factory:
            - @doctrine
            - "getRepository"
        arguments:
            - %opsite.entity.block.class%
