parameters:
    opsite_builder.security.page.allow_all.voter.class: OpSiteBuilder\Bundle\CoreBundle\Security\AllowAllPageVoter

services:
    opsite_builder.security.page.allow_all.voter:
        class: %opsite_builder.security.page.allow_all.voter.class%
        public: false
        tags:
            - { name: security.voter }
