parameters:
    opsite_builder.page.normalizer.class: OpSiteBuilder\Bundle\CoreBundle\Page\Normalizer\PageNormalizer
    opsite_builder.block.normalizer.class: OpSiteBuilder\Bundle\CoreBundle\Block\Normalizer\BlockNormalizer
    opsite_builder.page.post_normalizer.add_block.class: OpSiteBuilder\Bundle\CoreBundle\Page\Normalizer\AddBlockPostNormalizer
    opsite_builder.block_map_chain.normalizer.class: OpSiteBuilder\Bundle\CoreBundle\Block\Normalizer\BlockMapChainNormalizer
    opsite_builder.block_map.normalizer.class: OpSiteBuilder\Bundle\CoreBundle\Block\Normalizer\BlockMapNormalizer
    opsite_builder.tool_chain.normalizer.class: OpSiteBuilder\Bundle\CoreBundle\Tool\Normalizer\ToolChainNormalizer
    opsite_builder.tool.normalizer.class: OpSiteBuilder\Bundle\CoreBundle\Tool\Normalizer\ToolNormalizer

services:
    opsite_builder.page.normalizer:
        class: %opsite_builder.page.normalizer.class%
        arguments:
            - @opsite_builder.block.normalizer
            - @router.default
        tags:
             - { name: serializer.normalizer }

    opsite_builder.block.normalizer:
        class: %opsite_builder.block.normalizer.class%
        arguments:
            - @router.default
            - @opsite_builder.block.configuration.chain
        tags:
             - { name: serializer.normalizer }

    opsite_builder.page.post_normalizer.add_block:
        class: %opsite_builder.page.post_normalizer.add_block.class%
        arguments:
            - @cmf_routing.router

    opsite_builder.block_map_chain.normalizer:
        class: %opsite_builder.block_map_chain.normalizer.class%
        arguments:
            - @opsite_builder.block_map.normalizer
        tags:
             - { name: serializer.normalizer }

    opsite_builder.block_map.normalizer:
        class: %opsite_builder.block_map.normalizer.class%
        tags:
             - { name: serializer.normalizer }
