parameters:
    opsite_builder.twig_extension.block.class: OpSiteBuilder\Bundle\CoreBundle\Twig\BlockExtension
    opsite_builder.twig_extension.routing.class: OpSiteBuilder\Bundle\CoreBundle\Twig\RoutingExtension
    opsite_builder.twig_extension.serializer.class: OpSiteBuilder\Bundle\CoreBundle\Twig\SerializerExtension
    opsite_builder.twig_extension.angular.class: OpSiteBuilder\Bundle\CoreBundle\Twig\AngularExtension

services:
    opsite_builder.twig_extension.block:
        class: %opsite_builder.twig_extension.block.class%
        arguments:
            - @opsite_builder.block.configuration.chain
            - @opsite_builder.block.manager
            - @opsite_builder.block.map.chain
        public: false
        tags:
            - { name: twig.extension }

    opsite_builder.twig_extension.routing:
        class: %opsite_builder.twig_extension.routing.class%
        arguments:
            - @opsite_builder.routing.generator
            - @opsite_builder.route_configuration.chain
        public: false
        tags:
            - { name: twig.extension }

    opsite_builder.twig_extension.serializer:
        class: %opsite_builder.twig_extension.serializer.class%
        arguments:
            - @serializer
        public: false
        tags:
            - { name: twig.extension }

    opsite_builder.twig_extension.angular:
        class: %opsite_builder.twig_extension.angular.class%
        public: false
        tags:
            - { name: twig.extension }
